# Generated by Django 5.1.3 on 2025-01-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_condition', models.CharField(max_length=100)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacture_year', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('engine_capacity', models.CharField(max_length=100)),
                ('mileage', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
                ('image01', models.ImageField(upload_to='vehicles/')),
                ('image02', models.ImageField(upload_to='vehicles/')),
                ('image03', models.ImageField(upload_to='vehicles/')),
                ('image04', models.ImageField(upload_to='vehicles/')),
                ('image05', models.ImageField(upload_to='vehicles/')),
                ('image06', models.ImageField(upload_to='vehicles/')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
