# Generated by Django 5.1.3 on 2025-01-16 14:02

import django.utils.timezone
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_ads_delete_customuser'),
    ]

    operations = [
       migrations.AddField(
       model_name='ads',
       name='date',
       field=models.DateField(default=datetime.date.today),
)

    ]
