# Generated by Django 5.1.3 on 2025-01-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_ads_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='test')),
            ],
        ),
        migrations.RemoveField(
            model_name='ads',
            name='date',
        ),
    ]
