# Generated by Django 5.1.3 on 2025-01-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_test_remove_ads_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='date',
            field=models.DateField(auto_now_add=True, default=21.2),
            preserve_default=False,
        ),
    ]
