# Generated by Django 5.1.3 on 2025-01-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_ads_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='first_name',
        ),
        migrations.AddField(
            model_name='ads',
            name='contact',
            field=models.CharField(default=21.56, max_length=12),
            preserve_default=False,
        ),
    ]
