# Generated by Django 5.1.3 on 2025-01-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_alter_ads_image01_alter_ads_image02_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ads',
            new_name='VehicleAds',
        ),
    ]
