# Generated by Django 5.1.3 on 2025-01-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_rename_ads_vehicleads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleAds',
        ),
    ]
