# Generated by Django 5.1.3 on 2025-01-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_adsvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='myads_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=12)),
            ],
        ),
    ]
