# Generated by Django 5.1.3 on 2025-01-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_myads_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdsVehicle',
        ),
        migrations.DeleteModel(
            name='myads_model',
        ),
    ]
