# Generated by Django 5.1.3 on 2025-01-16 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_delete_adsvehicle_delete_myads_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleads',
            name='contact',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{10,12}$', 'Enter a valid phone number.')]),
        ),
    ]
