# Generated by Django 5.1.3 on 2025-01-17 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_alter_vehicleads_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehicleAds',
            new_name='Ads',
        ),
    ]
