# Generated by Django 5.1.3 on 2025-01-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_rename_vehicleads_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='date',
            field=models.DateField(),
        ),
    ]
