# Generated by Django 5.1.3 on 2025-01-17 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_alter_ads_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
