# Generated by Django 5.1.3 on 2025-01-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_alter_ads_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image01',
            field=models.ImageField(default=10.54, upload_to='vehicles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ads',
            name='image02',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='image03',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='image04',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='image05',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='image06',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles'),
        ),
    ]
