# Generated by Django 5.1.3 on 2025-01-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_alter_ads_image01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image01',
            field=models.ImageField(upload_to=''),
        ),
    ]
