# Generated by Django 5.1.3 on 2025-01-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_alter_ads_image01_alter_ads_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='info',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=models.IntegerField(max_length=100),
        ),
    ]
