# Generated by Django 5.1.3 on 2025-01-22 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
