# Generated by Django 5.1.3 on 2025-01-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_remove_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=models.IntegerField(),
        ),
    ]
