# Generated by Django 5.1.3 on 2025-01-22 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_alter_ads_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
