# Generated by Django 5.1.3 on 2025-01-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0032_alter_contact_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='myapp_contact',
        ),
    ]
