# Generated by Django 5.1.3 on 2025-01-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0033_alter_contact_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faq',
            table='myapp_faq',
        ),
    ]
